---
Name: opengraphmeta
After:
  - 'siteconfig/*'
Before:
  - 'mysite'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - OpenGraphMeta
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OpenGraphSiteConfigExtension
